version: '3.8'

services:
  dental_db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: dental_scheduler_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:1433"
    volumes:
      - sql_data:/var/opt/mssql
  
volumes:
  sql_data: